# HealthIndicators Plugin Config

# Text to appear at the beginning of the damage indicator.
# You can use color codes with '&'. (default: '&c❤ ')
indicator-prefix: '&c❤ '

# Special prefix that pops up when a crit lands. (default: '&e✯ ')
critical-indicator-prefix: '&e✯ '

# Time the damage indicator stays on screen (in secs)
# You have to use decimal (double) values (default: 2.0)
indicator-duration-seconds: 2.0